/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'strona-glowna': StronaGlowna;
    oferta: Oferta;
    galeria: Galeria;
    'krok-po-kroku': KrokPoKroku;
    tanatokosmetyka: Tanatokosmetyka;
    'zasilek-pogrzebowy': ZasilekPogrzebowy;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'strona-glowna': StronaGlownaSelect<false> | StronaGlownaSelect<true>;
    oferta: OfertaSelect<false> | OfertaSelect<true>;
    galeria: GaleriaSelect<false> | GaleriaSelect<true>;
    'krok-po-kroku': KrokPoKrokuSelect<false> | KrokPoKrokuSelect<true>;
    tanatokosmetyka: TanatokosmetykaSelect<false> | TanatokosmetykaSelect<true>;
    'zasilek-pogrzebowy': ZasilekPogrzebowySelect<false> | ZasilekPogrzebowySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Krótki opis tego, co przedstawia zdjęcie — dla czytników ekranu i SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Numer wyświetlany w nagłówku, stopce i na wszystkich stronach.
   */
  phone: string;
  locations?:
    | {
        label: string;
        name: string;
        street: string;
        postalCode?: string | null;
        city: string;
        /**
         * Zostaw puste — użyje globalnego numeru telefonu z góry strony.
         */
        phone?: string | null;
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strona-glowna".
 */
export interface StronaGlowna {
  id: string;
  hero?: {
    badge?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
    subtitle?: string | null;
    /**
     * Duże zdjęcie w tle sekcji głównej. Puste = zostaje zdjęcie domyślne.
     */
    image?: (string | null) | Media;
    ctaPrimaryLabel?: string | null;
    ctaSecondaryLabel?: string | null;
  };
  about?: {
    label?: string | null;
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    /**
     * Zdjęcie obok tekstu. Puste = zostaje zdjęcie domyślne.
     */
    image?: (string | null) | Media;
  };
  /**
   * Same karty usług pochodzą z zakładki „Oferta (usługi)".
   */
  servicesSection?: {
    label?: string | null;
    heading?: string | null;
    subtitle?: string | null;
  };
  cta?: {
    heading?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oferta".
 */
export interface Oferta {
  id: string;
  intro?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
  };
  /**
   * Edytuj treść istniejących usług. Liczba usług i ich adresy URL są stałe.
   */
  services?:
    | {
        /**
         * Stała część adresu /oferta/… — nieedytowalna.
         */
        slug: string;
        title: string;
        shortDesc: string;
        description?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Puste = zostaje zdjęcie domyślne.
         */
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria".
 */
export interface Galeria {
  id: string;
  intro?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
  };
  footerNote?: string | null;
  /**
   * Dodaj dowolną liczbę zdjęć. Galeria pokazuje tylko zdjęcia tutaj wgrane.
   */
  images?:
    | {
        image?: (string | null) | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "krok-po-kroku".
 */
export interface KrokPoKroku {
  id: string;
  intro?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
  };
  /**
   * Numery kroków (01, 02, …) nadawane są automatycznie według kolejności.
   */
  steps?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  sidebar?: {
    reminderLabel?: string | null;
    reminderHeading?: string | null;
    reminderText?: string | null;
    zasilekLabel?: string | null;
    zasilekText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tanatokosmetyka".
 */
export interface Tanatokosmetyka {
  id: string;
  title?: string | null;
  /**
   * Puste = zostaje zdjęcie domyślne.
   */
  image?: (string | null) | Media;
  description?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zasilek-pogrzebowy".
 */
export interface ZasilekPogrzebowy {
  id: string;
  intro?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
  };
  whatIs?: {
    label?: string | null;
    heading?: string | null;
    text?: string | null;
  };
  whoQualifies?: {
    heading?: string | null;
    intro?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  amount?: {
    heading?: string | null;
    amountLabel?: string | null;
    amountValue?: string | null;
    amountNote?: string | null;
    text?: string | null;
  };
  documents?: {
    heading?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  deadline?: {
    heading?: string | null;
    text?: string | null;
  };
  ctaBox?: {
    heading?: string | null;
    text?: string | null;
  };
  /**
   * Niewidoczne na stronie — używane przez Google (dane strukturalne FAQ). Trzymaj zgodne z treścią powyżej.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  locations?:
    | T
    | {
        label?: T;
        name?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        phone?: T;
        hours?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strona-glowna_select".
 */
export interface StronaGlownaSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleLine2?: T;
        subtitle?: T;
        image?: T;
        ctaPrimaryLabel?: T;
        ctaSecondaryLabel?: T;
      };
  about?:
    | T
    | {
        label?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        image?: T;
      };
  servicesSection?:
    | T
    | {
        label?: T;
        heading?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oferta_select".
 */
export interface OfertaSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
      };
  services?:
    | T
    | {
        slug?: T;
        title?: T;
        shortDesc?: T;
        description?:
          | T
          | {
              text?: T;
              id?: T;
            };
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria_select".
 */
export interface GaleriaSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
      };
  footerNote?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "krok-po-kroku_select".
 */
export interface KrokPoKrokuSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  sidebar?:
    | T
    | {
        reminderLabel?: T;
        reminderHeading?: T;
        reminderText?: T;
        zasilekLabel?: T;
        zasilekText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tanatokosmetyka_select".
 */
export interface TanatokosmetykaSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  description?:
    | T
    | {
        text?: T;
        id?: T;
      };
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zasilek-pogrzebowy_select".
 */
export interface ZasilekPogrzebowySelect<T extends boolean = true> {
  intro?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
      };
  whatIs?:
    | T
    | {
        label?: T;
        heading?: T;
        text?: T;
      };
  whoQualifies?:
    | T
    | {
        heading?: T;
        intro?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  amount?:
    | T
    | {
        heading?: T;
        amountLabel?: T;
        amountValue?: T;
        amountNote?: T;
        text?: T;
      };
  documents?:
    | T
    | {
        heading?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  deadline?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  ctaBox?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}